
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 23;
  public static final int RBRACK = 14;
  public static final int AND = 30;
  public static final int OVER = 24;
  public static final int LT = 19;
  public static final int ELSE = 3;
  public static final int TRUTH = 33;
  public static final int PLUS = 21;
  public static final int OR = 29;
  public static final int RPAREN = 10;
  public static final int INT = 5;
  public static final int LTE = 25;
  public static final int SEMI = 11;
  public static final int WHILE = 7;
  public static final int NOT = 28;
  public static final int LBRACK = 13;
  public static final int RETURN = 8;
  public static final int ERROR = 34;
  public static final int IF = 2;
  public static final int RCBRACK = 16;
  public static final int GT = 20;
  public static final int LPAREN = 9;
  public static final int ID = 31;
  public static final int GTE = 26;
  public static final int NUM = 32;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int MINUS = 22;
  public static final int error = 1;
  public static final int LCBRACK = 15;
  public static final int EQ = 18;
  public static final int ASSIGN = 17;
  public static final int BOOL = 4;
  public static final int NEQ = 27;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "BOOL",
  "INT",
  "VOID",
  "WHILE",
  "RETURN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COMMA",
  "LBRACK",
  "RBRACK",
  "LCBRACK",
  "RCBRACK",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LTE",
  "GTE",
  "NEQ",
  "NOT",
  "OR",
  "AND",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

